Vagrant.configure('2') do |config|
  config.vm.box_check_update = false

  config.vm.define 'master' do |master|
    master.vm.hostname = 'master'
    master.vm.box = 'bento/ubuntu-24.04'
    master.vm.network :private_network, ip: '192.168.56.101'
  end

  config.vm.define 'worker' do |worker|
    worker.vm.hostname = 'worker'
    worker.vm.box = 'bento/ubuntu-24.04'
    worker.vm.network :private_network, ip: '192.168.56.103'
  end

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.memory = '3072'
    vb.cpus = 4
  end

  config.vm.provision 'shell', inline: <<-SHELL
    ROOT_PASSWORD="1"
    echo "root:$ROOT_PASSWORD" | sudo chpasswd
    sudo apt update
    sudo apt upgrade -y
    sudo apt install net-tools -y
    sudo swapoff -a
    sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  SHELL
  # config.vm.provision 'shell', path: 'script.sh'
end
