version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
  mongo:
    image: mongo:5.0
    ports:
      - "4000:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
