Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  #config.hostmanager.manage_guest = true
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "master1"
  config.vm.network "private_network", ip: "192.168.56.101"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end

  #config.vm.provision "shell", inline: <<-SHELL
   # sudo apt-get update
  #SHELL
end
