Vagrant.configure('2') do |config|
  config.vm.box_check_update = false

  config.vm.define 'master' do |master|
    master.vm.hostname = 'master'
    master.vm.box = 'ubuntu/focal64'
    master.vm.network :private_network, ip: '192.168.56.101'
  end

  config.vm.define 'worker1' do |worker1|
    worker1.vm.hostname = 'worker1'
    worker1.vm.box = 'ubuntu/focal64'
    worker1.vm.network :private_network, ip: '192.168.56.111'
  end

  config.vm.define 'worker2' do |worker2|
    worker2.vm.hostname = 'worker2'
    worker2.vm.box = 'ubuntu/focal64'
    worker2.vm.network :private_network, ip: '192.168.56.112'
  end

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.memory = '3072'
    vb.cpus = 4
  end

  config.vm.provision 'shell', inline: <<-SHELL
    ROOT_PASSWORD="1"
    echo "root:$ROOT_PASSWORD" | sudo chpasswd
    sudo apt-get update
    # sudo apt upgrade -y
    sudo apt-get install net-tools -y
    sudo swapoff -a
    sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  SHELL
  # config.vm.provision 'shell', path: 'script.sh'
end
